name: Godenowl CICD

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - 'src/**'
      - '.github/workflows/cicd.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker pull $DOCKERHUB_USERNAME/go-devops-test:latest
          cd src && docker build -t $DOCKERHUB_USERNAME/go-devops-test:$IMAGE_TAG -f Dockerfile .

      - name: Push images to Docker Hub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker push $DOCKERHUB_USERNAME/go-devops-test:$IMAGE_TAG
          docker tag $DOCKERHUB_USERNAME/go-devops-test:$IMAGE_TAG $DOCKERHUB_USERNAME/godenowl:latest
          docker push $DOCKERHUB_USERNAME/go-devops-test:latest
