name: CI build

on:
  push:
    branches:
      - 'master'
env: 
  username: ${{ secrets.DOCKERHUB_USERNAME }}
  password: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3
      
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      
      - name: Install dependencies
        run: npm install
        working-directory: src
        
      - name: Test
        run: |
          if npm test; then
            echo "test success"
          else
            echo "test failure"
            exit 1
          fi
        working-directory: src
      
  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      # - name: Check out
      #   uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.username }}
          password: ${{ env.password }}

      - name: Build and push image
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          docker build -t $DOCKERHUB_USERNAME/go-devops-testt:latest .
          docker push $DOCKERHUB_USERNAME/go-devops-test:latest

