name: CI/CD build

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
    paths:
      - 'src/**'
      - '.github/workflows/main.yml'
      
jobs:
  build:
    runs-on: ubuntu-latest
    # needs: test

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker pull $DOCKERHUB_USERNAME/go-devops-test:latest
          cd src
          docker build -t "$DOCKERHUB_USERNAME/go-devops-test:latest" .
          docker push "$DOCKERHUB_USERNAME/go-devops-test:latest"

  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Check out
        uses: actions/checkout@v3
      
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      
      - name: Install dependencies
        run: npm install
        working-directory: src
        
      - name: Test
        run: |
          if npm test; then
            echo "test success"
          else
            echo "test failure"
            exit 1
          fi
        working-directory: src
      

  deploy:
      runs-on: self-hosted
      steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          SA_KEY_JSON: "${{ secrets.GCP_SA_KEY_JSON }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Install kubectl
        run: gcloud components install kubectl

      - name: Check kubectl version
        run: kubectl version --client

      - name: Use gcloud CLI
        run: gcloud info

      - name: Docker auth
        run: gcloud auth configure-docker us-west4-docker.pkg.dev --quiet

      - name: Set version
        id: version
        #run: echo "::set-output name=VERSION::$(git rev-parse --short HEAD)"
        run: echo "VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT


      - name: Build and push the docker image
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          VERSION: ${{ steps.version.outputs.VERSION }}
        run: |
          DOCKER_IMAGE="us-west2-docker.pkg.dev/${PROJECT_ID}/devops/:${VERSION}"
          gcloud auth configure-docker us-west4-a-docker.pkg.dev
          docker build -t $DOCKER_IMAGE .
          docker push $DOCKER_IMAGE
          
