name: CI/CD build

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
    paths:
      - 'src/**'
      - '.github/workflows/main.yml'
      
jobs:
  build:
    runs-on: ubuntu-latest
    # needs: test

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker pull $DOCKERHUB_USERNAME/go-devops-test:latest
          cd src
          docker build -t "$DOCKERHUB_USERNAME/go-devops-test:latest" .
          docker push "$DOCKERHUB_USERNAME/go-devops-test:latest"

  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Check out
        uses: actions/checkout@v3
      
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      
      - name: Install dependencies
        run: npm install
        working-directory: src
        
      - name: Test
        run: |
          if npm test; then
            echo "test success"
          else
            echo "test failure"
            exit 1
          fi
        working-directory: src
      

  deploy:
      runs-on: ubuntu-latest
      needs: [build, test]
      
      steps:
        - name: Deploy to Cloud Run
          uses: actions/checkout@v3
        
        - name: Set up GCLoud CLI
          uses: google-github-actions/auth@v2
          with:
            credentials_json: "${{ secrets.GCP_SA_KEY_JSON }}"
            version: "290.0.1"
            SA_KEY_JSON: ${{ secrets.GCP_SA_KEY_JSON }}
            PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
            
        - name: Build and push the docker image
          env:
            PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
            VERSION: ${{ steps.version.outputs.VERSION }}
          run: |
            DOCKER_IMAGE="us-west4-docker.pkg.dev/${PROJECT_ID}/devops/dnnq2012:${VERSION}"
            gcloud auth configure-docker us-west4-a-docker.pkg.dev
            docker build -t $DOCKER_IMAGE .
            docker push $DOCKER_IMAGE
