name: CI build

on:
  push:
    branches:
      - 'master'
      
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3
      
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      
      - name: Install dependencies
        run: npm install
        working-directory: src
        
      - name: Test
        run: |
          if npm test; then
            echo "test success"
          else
            echo "test failure"
            exit 1
          fi
        working-directory: src
      
  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      # - name: Check out
      #   uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          ls /data/
          cd src && docker build -t "$DOCKERHUB_USERNAME/go-devops-test:latest" .
          docker push "$DOCKERHUB_USERNAME/go-devops-test:latest"
  deloy:
    runs-on: ubuntu-latest
    name: deploy
    needs: [test, build]
    if: github.ref == 'refs/heads/master'
    environment:  ${{ github.ref_name }}
    steps:
      - name: Deploy to Google Cloud VM
        env:
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        run: |
          
          echo "$GCP_SERVICE_ACCOUNT_KEY" > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json --project=iron-potion-399705
          gcloud compute ssh instance-1 --zone=asia-southeast1-b --command "~/deploy.sh"
          rm gcp-key.json
